### ISSUE TITLE
Página Sobre

### ISSUE THREAD

**Issue by mrchristianrogerio** [christianrogerio/github-master#4]
Vocês poderiam criar uma página Sobre?

**Comment by christianrogerio** [comment]
> Vocês poderiam criar uma página Sobre?

A página está em produção.

**Comment by mrchristianrogerio** [comment]
Obrigado. Vou verificar.

Em sáb., 9 de mai. de 2020 às 20:27, Christian Rogério Câmara de Abreu <
notifications@github.com> escreveu:
